name: local_auth


flutter:
  uses-material-design: true
  # plugin:
  #   platforms:
  #     android:
  #       package: io.flutter.plugins.localauth
  #       pluginClass: LocalAuthPlugin
  #     ios:
  #       pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  intl: ##">=0.15.1 <0.17.0"
  platform: 
  flutter_plugin_android_lifecycle: ^2.0.0

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.7.0 <3.0.0"
